# Generated by Django 2.1 on 2020-02-29 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Urlconfiguratin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_url', models.URLField()),
                ('host_name', models.CharField(max_length=20)),
                ('describe', models.CharField(max_length=100, null=True)),
                ('data_time', models.DateTimeField(auto_now_add=True)),
                ('updata_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urlconfiguratin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'urlconfiguratin',
                'ordering': ['-data_time'],
            },
        ),
    ]
