# Generated by Django 2.1 on 2020-01-01 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('use_case', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='operation_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
                ('result', models.CharField(max_length=50)),
                ('data_time', models.DateTimeField(auto_now_add=True)),
                ('function_time', models.CharField(max_length=100)),
                ('use_case_mode', models.CharField(max_length=10)),
                ('dy_value', models.CharField(max_length=200)),
                ('use', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='use_case.Usecase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operation_information',
            },
        ),
    ]
