# Generated by Django 2.1 on 2020-02-29 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entry_name', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50, verbose_name='模块名称')),
                ('module_order', models.IntegerField(verbose_name='模块运行顺序')),
                ('test_user', models.CharField(max_length=20, verbose_name='测试负责人')),
                ('simple_desc', models.CharField(max_length=100, null=True, verbose_name='简要描述')),
                ('other_desc', models.CharField(max_length=100, null=True, verbose_name='其他信息')),
                ('data_time', models.DateTimeField(auto_now_add=True)),
                ('updata_time', models.DateTimeField(auto_now=True)),
                ('belong_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moduleInfo', to='entry_name.ProjectInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moduleInfo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ModuleInfo',
                'ordering': ['-data_time'],
            },
        ),
    ]
