# Generated by Django 2.1 on 2020-01-01 01:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('url_configuration', '0001_initial'),
        ('module_name', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usecase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=20)),
                ('case_url', models.CharField(max_length=200)),
                ('case_order', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=999)])),
                ('req', models.CharField(default='GET', max_length=10)),
                ('header_key', models.TextField(null=True)),
                ('header_value', models.TextField(null=True)),
                ('value_type', models.CharField(default='form-data', max_length=10)),
                ('data_key', models.TextField(null=True)),
                ('data_type', models.TextField(null=True)),
                ('data_value', models.TextField(null=True)),
                ('json_keyvalue', models.TextField(null=True)),
                ('dy_key', models.TextField(null=True)),
                ('dy_type', models.TextField(null=True)),
                ('dy_value', models.TextField(null=True)),
                ('all_extract', models.TextField(null=True)),
                ('describe', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(default='-', max_length=50, null=True)),
                ('all_extract_state', models.TextField(null=True)),
                ('data_time', models.DateTimeField(auto_now_add=True)),
                ('updata_time', models.DateTimeField(auto_now=True)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('use_case1', models.ForeignKey(default='null', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='url_configuration.Urlconfiguratin')),
                ('usecase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='module_name.ModuleInfo')),
            ],
            options={
                'db_table': 'usecase',
                'ordering': ['-data_time'],
            },
        ),
    ]
