# Generated by Django 2.1 on 2020-01-01 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('responsible_name', models.CharField(max_length=20, verbose_name='负责人')),
                ('test_user', models.CharField(max_length=20, verbose_name='测试人员')),
                ('dev_user', models.CharField(max_length=20, verbose_name='开发人员')),
                ('all_use', models.CharField(default='0/0', max_length=20, verbose_name='关联模块/用例总数')),
                ('publish_app', models.CharField(max_length=20, verbose_name='发布应用')),
                ('simple_desc', models.CharField(max_length=100, null=True, verbose_name='简要描述')),
                ('other_desc', models.CharField(max_length=100, null=True, verbose_name='其他信息')),
                ('data_time', models.DateTimeField(auto_now_add=True)),
                ('updata_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectInfo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProjectInfo',
                'ordering': ['data_time'],
            },
        ),
    ]
